services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: auth_service
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
